import { Tour } from '@/types'

export const mockTours: Tour[] = [
  {
    id: '1',
    title: 'Тайны Петербургских дворов',
    description: 'Погрузитесь в атмосферу старого Петербурга, где каждый двор хранит свою уникальную историю. Узнайте о жизни знаменитых писателей и художников.',
    city: 'Санкт-Петербург',
    category: 'История',
    duration: 90,
    distance: 3.5,
    price: 499,
    rating: 4.9,
    reviewsCount: 234,
    image: './assets/imgAndLogo/SanktPetersburg.jpg',
    author: {
      id: 'author-1',
      name: 'Анна Петрова',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      bio: 'Историк, влюбленная в Петербург',
      toursCount: 12,
      rating: 4.9,
      verified: true,
    },
    points: [],
    tags: ['Архитектура', 'Литература', 'Пешеходная'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '11',
    title: 'Золотое кольцо: Владимир и Суздаль',
    description: 'Путешествие по древним городам Золотого кольца. Узнайте историю Древней Руси и насладитесь красотой белокаменной архитектуры.',
    city: 'Владимир',
    category: 'История',
    duration: 180,
    distance: 8,
    price: 799,
    rating: 4.7,
    reviewsCount: 156,
    image: './assets/imgAndLogo/Zolotoe_Kotsojpg.jpg',
    author: {
      id: 'author-11',
      name: 'Елена Волкова',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      bio: 'Экскурсовод по Золотому кольцу',
      toursCount: 15,
      rating: 4.7,
      verified: true,
    },
    points: [],
    tags: ['История', 'Архитектура', 'Автобусная'],
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '12',
    title: 'Казанский Кремль: перекресток культур',
    description: 'Исследуйте уникальный симбиоз русской и татарской культур в сердце Казани. Мечети, церкви и древние стены расскажут свою историю.',
    city: 'Казань',
    category: 'Культура',
    duration: 120,
    distance: 4,
    price: 599,
    rating: 4.8,
    reviewsCount: 203,
    image: './assets/imgAndLogo/Kazan.jpg',
    author: {
      id: 'author-12',
      name: 'Рустам Галеев',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      bio: 'Краевед и историк Казани',
      toursCount: 9,
      rating: 4.8,
      verified: true,
    },
    points: [],
    tags: ['Культура', 'Архитектура', 'Пешеходная'],
    createdAt: '2024-01-22T00:00:00Z',
  },
  {
    id: '13',
    title: 'Екатеринбург: уральская столица',
    description: 'Откройте для себя город на границе Европы и Азии. Узнайте о промышленной истории Урала и современных достижениях.',
    city: 'Екатеринбург',
    category: 'История',
    duration: 150,
    distance: 6,
    price: 699,
    rating: 4.6,
    reviewsCount: 134,
    image: './assets/imgAndLogo/Ekaterinburg.jpg',
    author: {
      id: 'author-13',
      name: 'Алексей Уралов',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      bio: 'Краевед Урала',
      toursCount: 7,
      rating: 4.6,
      verified: true,
    },
    points: [],
    tags: ['История', 'Промышленность', 'Пешеходная'],
    createdAt: '2024-01-25T00:00:00Z',
  },
  {
    id: '14',
    title: 'Новосибирск: сибирский мегаполис',
    description: 'Познакомьтесь с крупнейшим городом Сибири. От древних поселений до современных небоскребов - вся история в одном городе.',
    city: 'Новосибирск',
    category: 'Современность',
    duration: 135,
    distance: 5.5,
    price: 549,
    rating: 4.5,
    reviewsCount: 98,
    image: './assets/imgAndLogo/Krasnoyarsk.jpg',
    author: {
      id: 'author-14',
      name: 'Мария Сибирская',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      bio: 'Гид по Сибири',
      toursCount: 11,
      rating: 4.5,
      verified: true,
    },
    points: [],
    tags: ['Современность', 'Архитектура', 'Пешеходная'],
    createdAt: '2024-01-28T00:00:00Z',
  },
  {
    id: '15',
    title: 'Владивосток: ворота в Азию',
    description: 'Исследуйте самый восточный город России. Морская история, уникальная архитектура и потрясающие виды на Тихий океан.',
    city: 'Владивосток',
    category: 'Природа',
    duration: 165,
    distance: 7,
    price: 899,
    rating: 4.9,
    reviewsCount: 87,
    image: './assets/imgAndLogo/Vladivostok.jpg',
    author: {
      id: 'author-15',
      name: 'Игорь Морской',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      bio: 'Морской историк и гид',
      toursCount: 6,
      rating: 4.9,
      verified: true,
    },
    points: [],
    tags: ['Природа', 'Море', 'Пешеходная'],
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '16',
    title: 'Краснодар: южная столица',
    description: 'Погрузитесь в атмосферу южного города. Казачья история, кубанские традиции и современная жизнь в одном месте.',
    city: 'Краснодар',
    category: 'Культура',
    duration: 120,
    distance: 4.5,
    price: 499,
    rating: 4.4,
    reviewsCount: 112,
    image: './assets/imgAndLogo/Krasnodar.jpg',
    author: {
      id: 'author-16',
      name: 'Светлана Кубанская',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      bio: 'Краевед Кубани',
      toursCount: 8,
      rating: 4.4,
      verified: true,
    },
    points: [],
    tags: ['Культура', 'Казачество', 'Пешеходная'],
    createdAt: '2024-02-03T00:00:00Z',
  },
  {
    id: '17',
    title: 'Ростов-на-Дону: ворота Кавказа',
    description: 'Откройте для себя город, где встречаются Европа и Азия. Богатая история, многонациональная культура и южное гостеприимство.',
    city: 'Ростов-на-Дону',
    category: 'Культура',
    duration: 140,
    distance: 5,
    price: 599,
    rating: 4.6,
    reviewsCount: 89,
    image: './assets/imgAndLogo/Rostov_na_donu.jpg',
    author: {
      id: 'author-17',
      name: 'Дмитрий Донской',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      bio: 'Историк Дона',
      toursCount: 10,
      rating: 4.6,
      verified: true,
    },
    points: [],
    tags: ['Культура', 'История', 'Пешеходная'],
    createdAt: '2024-02-05T00:00:00Z',
  },
  {
    id: '18',
    title: 'Волгоград: город-герой',
    description: 'Пройдите по местам великой битвы. Узнайте о подвиге защитников Сталинграда и современной жизни города-героя.',
    city: 'Волгоград',
    category: 'История',
    duration: 180,
    distance: 8,
    price: 699,
    rating: 4.8,
    reviewsCount: 145,
    image: './assets/imgAndLogo/Volgograd.jpg',
    author: {
      id: 'author-18',
      name: 'Александр Волжский',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      bio: 'Военный историк',
      toursCount: 13,
      rating: 4.8,
      verified: true,
    },
    points: [],
    tags: ['История', 'Война', 'Пешеходная'],
    createdAt: '2024-02-08T00:00:00Z',
  },
  {
    id: '19',
    title: 'Красноярск: сердце Сибири',
    description: 'Исследуйте один из крупнейших городов Сибири. От древних стоянок до современных технологий - вся история региона.',
    city: 'Красноярск',
    category: 'История',
    duration: 150,
    distance: 6,
    price: 649,
    rating: 4.5,
    reviewsCount: 76,
    image: './assets/imgAndLogo/Krasnoyarsk.jpg',
    author: {
      id: 'author-19',
      name: 'Елена Красноярская',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      bio: 'Краевед Сибири',
      toursCount: 9,
      rating: 4.5,
      verified: true,
    },
    points: [],
    tags: ['История', 'Сибирь', 'Пешеходная'],
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '20',
    title: 'Пермь: уральская столица культуры',
    description: 'Откройте для себя культурную столицу Урала. Театры, музеи, современное искусство и богатая история города.',
    city: 'Пермь',
    category: 'Культура',
    duration: 135,
    distance: 5.5,
    price: 549,
    rating: 4.4,
    reviewsCount: 93,
    image: './assets/imgAndLogo/Perm.jpg',
    author: {
      id: 'author-20',
      name: 'Анна Пермская',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      bio: 'Культуролог и гид',
      toursCount: 7,
      rating: 4.4,
      verified: true,
    },
    points: [],
    tags: ['Культура', 'Искусство', 'Пешеходная'],
    createdAt: '2024-02-12T00:00:00Z',
  },
  {
    id: '2',
    title: 'Московское метро: подземный дворец',
    description: 'Исследуйте архитектурные шедевры московского метрополитена. Каждая станция — настоящее произведение искусства.',
    city: 'Москва',
    category: 'Архитектура',
    duration: 120,
    distance: 5,
    price: 599,
    rating: 4.8,
    reviewsCount: 189,
    image: './assets/imgAndLogo/Moskov_metro.jpg',
    author: {
      id: 'author-2',
      name: 'Дмитрий Соколов',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      bio: 'Архитектор и городской исследователь',
      toursCount: 8,
      rating: 4.8,
      verified: true,
    },
    points: [],
    tags: ['Метро', 'СССР', 'Искусство'],
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Золотое кольцо: путь к истокам',
    description: 'Откройте для себя древние города России, их храмы и монастыри. Прикоснитесь к истории русского православия.',
    city: 'Владимир',
    category: 'Культура',
    duration: 180,
    distance: 8,
    price: 799,
    rating: 5.0,
    reviewsCount: 156,
    image: 'https://images.unsplash.com/photo-1513326738677-b964603b136d?w=600',
    author: {
      id: 'author-3',
      name: 'Елена Волкова',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      bio: 'Искусствовед и экскурсовод',
      toursCount: 15,
      rating: 5.0,
      verified: true,
    },
    points: [],
    tags: ['Храмы', 'История', 'Религия'],
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    title: 'Казань: легенды татарского народа',
    description: 'Познакомьтесь с уникальной культурой татарского народа через истории и легенды древней Казани.',
    city: 'Казань',
    category: 'Традиции',
    duration: 150,
    distance: 6,
    price: 699,
    rating: 4.9,
    reviewsCount: 201,
    image: './assets/imgAndLogo/Kazan_legendi.jpg',
    author: {
      id: 'author-4',
      name: 'Рустам Ахметов',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      bio: 'Знаток татарской культуры',
      toursCount: 10,
      rating: 4.9,
      verified: true,
    },
    points: [],
    tags: ['Культура', 'Легенды', 'Кремль'],
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '5',
    title: 'Екатеринбург: граница двух миров',
    description: 'Исследуйте город на границе Европы и Азии. История, индустриальное наследие и современная культура.',
    city: 'Екатеринбург',
    category: 'История',
    duration: 120,
    distance: 4.5,
    price: 549,
    rating: 4.7,
    reviewsCount: 145,
    image: './assets/imgAndLogo/Ekaterinburg.jpg',
    author: {
      id: 'author-5',
      name: 'Михаил Уральский',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      bio: 'Краевед и журналист',
      toursCount: 7,
      rating: 4.7,
      verified: true,
    },
    points: [],
    tags: ['Урал', 'Промышленность', 'История'],
    createdAt: '2024-01-25T00:00:00Z',
  },
  {
    id: '6',
    title: 'Сочи: субтропический рай',
    description: 'Откройте для себя природное богатство и историю курортного города на побережье Черного моря.',
    city: 'Сочи',
    category: 'Природа',
    duration: 135,
    distance: 7,
    price: 649,
    rating: 4.8,
    reviewsCount: 178,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
    author: {
      id: 'author-6',
      name: 'Светлана Морская',
      avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
      bio: 'Биолог и эколог',
      toursCount: 9,
      rating: 4.8,
      verified: true,
    },
    points: [],
    tags: ['Природа', 'Море', 'Горы'],
    createdAt: '2024-02-05T00:00:00Z',
  },
]


