import { Tour } from '@/types'

export const mockTours: Tour[] = [
  {
    id: '1',
    title: 'Тайны Петербургских дворов',
    description: 'Погрузитесь в атмосферу старого Петербурга, где каждый двор хранит свою уникальную историю. Узнайте о жизни знаменитых писателей и художников.',
    city: 'Санкт-Петербург',
    category: 'История',
    duration: 90,
    distance: 3.5,
    price: 499,
    rating: 4.9,
    reviewsCount: 234,
    image: 'https://images.unsplash.com/photo-1555991438-b87d68cb3e1f?w=600',
    author: {
      id: 'author-1',
      name: 'Анна Петрова',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      bio: 'Историк, влюбленная в Петербург',
      toursCount: 12,
      rating: 4.9,
      verified: true,
    },
    points: [],
    tags: ['Архитектура', 'Литература', 'Пешеходная'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Московское метро: подземный дворец',
    description: 'Исследуйте архитектурные шедевры московского метрополитена. Каждая станция — настоящее произведение искусства.',
    city: 'Москва',
    category: 'Архитектура',
    duration: 120,
    distance: 5,
    price: 599,
    rating: 4.8,
    reviewsCount: 189,
    image: 'https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=600',
    author: {
      id: 'author-2',
      name: 'Дмитрий Соколов',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      bio: 'Архитектор и городской исследователь',
      toursCount: 8,
      rating: 4.8,
      verified: true,
    },
    points: [],
    tags: ['Метро', 'СССР', 'Искусство'],
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Золотое кольцо: путь к истокам',
    description: 'Откройте для себя древние города России, их храмы и монастыри. Прикоснитесь к истории русского православия.',
    city: 'Владимир',
    category: 'Культура',
    duration: 180,
    distance: 8,
    price: 799,
    rating: 5.0,
    reviewsCount: 156,
    image: 'https://images.unsplash.com/photo-1513326738677-b964603b136d?w=600',
    author: {
      id: 'author-3',
      name: 'Елена Волкова',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      bio: 'Искусствовед и экскурсовод',
      toursCount: 15,
      rating: 5.0,
      verified: true,
    },
    points: [],
    tags: ['Храмы', 'История', 'Религия'],
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    title: 'Казань: легенды татарского народа',
    description: 'Познакомьтесь с уникальной культурой татарского народа через истории и легенды древней Казани.',
    city: 'Казань',
    category: 'Традиции',
    duration: 150,
    distance: 6,
    price: 699,
    rating: 4.9,
    reviewsCount: 201,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600',
    author: {
      id: 'author-4',
      name: 'Рустам Ахметов',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      bio: 'Знаток татарской культуры',
      toursCount: 10,
      rating: 4.9,
      verified: true,
    },
    points: [],
    tags: ['Культура', 'Легенды', 'Кремль'],
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '5',
    title: 'Екатеринбург: граница двух миров',
    description: 'Исследуйте город на границе Европы и Азии. История, индустриальное наследие и современная культура.',
    city: 'Екатеринбург',
    category: 'История',
    duration: 120,
    distance: 4.5,
    price: 549,
    rating: 4.7,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600',
    author: {
      id: 'author-5',
      name: 'Михаил Уральский',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      bio: 'Краевед и журналист',
      toursCount: 7,
      rating: 4.7,
      verified: true,
    },
    points: [],
    tags: ['Урал', 'Промышленность', 'История'],
    createdAt: '2024-01-25T00:00:00Z',
  },
  {
    id: '6',
    title: 'Сочи: субтропический рай',
    description: 'Откройте для себя природное богатство и историю курортного города на побережье Черного моря.',
    city: 'Сочи',
    category: 'Природа',
    duration: 135,
    distance: 7,
    price: 649,
    rating: 4.8,
    reviewsCount: 178,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
    author: {
      id: 'author-6',
      name: 'Светлана Морская',
      avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
      bio: 'Биолог и эколог',
      toursCount: 9,
      rating: 4.8,
      verified: true,
    },
    points: [],
    tags: ['Природа', 'Море', 'Горы'],
    createdAt: '2024-02-05T00:00:00Z',
  },
]

